name: LW Inline Scan
# TODO: Leverage Terraform backend maintenance of state file (https://www.terraform.io/docs/language/settings/backends/s3.html)
# Controls when the action will run. 
on:
  repository_dispatch:
    types: [scan]
  workflow_dispatch:
  pull_request:
    branches: [deploy-container]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  BuildAndScan:
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Build action
        run: | 
          npm ci
          npm run build


      - name: Build the latest Docker image
        run: docker build . -t bryancross:test-image
  
      - name: Download lw-scanner
        run: |
          sudo curl -LJO https://github.com/lacework/lacework-vulnerability-scanner/releases/download/v0.1.2/lw-scanner-linux-amd64
          sudo mv lw-scanner-linux-amd64 lw-scanner
          sudo chmod +x lw-scanner

      - name: Scan image
        run: | 
          printf ".\ntrue\nfalse" | ./lw-scanner config data
          ./lw-scanner evaluate bryancross test-image -t ${{ secrets.LW_ACCESS_TOKEN }} -n ${{ secrets.LW_ACCOUNT_NAME }} 

      - name: Transform results to SARIF
        run: | 
          npm run convert -- -s $(find . -type f -name 'evaluation*') 

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          # sarif_file: ./SARIF-examples/SARIF-minimal.sarif.json
          #sarif_file: ./SARIF-examples/SARIF-complete.sarif.json
          sarif_file: ./report.sarif.json

